---
- name: create rsyslog dir
  file:
    state: directory
    path: '{{ awx_debian_home }}/rsyslog/conf.d'
    owner: "{{ awx_debian_user }}"
    group: "{{ awx_debian_user }}"
    mode: 0775

- name: create supervisor dir
  file:
    state: directory
    path: /etc/supervisor
    owner: "{{ awx_debian_user }}"
    group: "{{ awx_debian_user }}"
    mode: 0775

- name: Install rsyslog.conf
  template:
    src: rsyslog.conf.j2
    dest: '{{ awx_debian_home }}/rsyslog/rsyslog.conf'
    owner: "{{ awx_debian_user }}"
    group: "{{ awx_debian_user }}"
    mode: 0664

- name: install supervisor files
  template:
    src: '{{ item }}.j2'
    dest: '/etc/supervisor/awx-{{ item }}'
    owner: "{{ awx_debian_user }}"
    group: "{{ awx_debian_user }}"
    mode: 0664
  with_items:
    - supervisor.conf
    - supervisor_task.conf

- name: Install systemd unit files for AWX and dependent services
  template:
    src:  "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    group: "{{ awx_debian_user }}"
    mode: 0770
  with_items:
    - awx-supervisor.service
    - awx-supervisor_task.service
    - awx-rsyslog.service

- name: Start AWX Services
  systemd:
    name: "{{ item }}"
    state: started
    daemon_reload: yes
    enabled: yes
  with_items:
    - awx-rsyslog
    - awx-supervisor
    - awx-supervisor_task

- name: Set AWX URL to use https if SSL is Enabled
  set_fact:
    awx_debian_url: "https://{{ awx_debian_fqdn }}"
  when: awx_debian_nginx_ssl

- name: Add Hosts Entry {{ ansible_default_ipv4.address }} {{ awx_debian_fqdn }}
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}"
    line:  "{{ ansible_default_ipv4.address }} {{ awx_debian_fqdn }}"

- name: Set AWX Base URL
  uri:
    url:      "{{ awx_debian_url }}/api/v2/settings/system/"
    user:     "{{ awx_debian_admin }}"
    password: "{{ awx_debian_pw }}"
    force_basic_auth: yes
    follow_redirects: all
    validate_certs: no
    method: PUT
    timeout: 60
    body: '{"ACTIVITY_STREAM_ENABLED":true,
            "ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC":false,
            "ORG_ADMINS_CAN_SEE_ALL_USERS":true,
            "MANAGE_ORGANIZATION_AUTH":true,
            "TOWER_ADMIN_ALERTS":true,
            "TOWER_URL_BASE":"{{ awx_debian_url }}",
            "REMOTE_HOST_HEADERS":["HTTP_X_FORWARDED_FOR","REMOTE_ADDR","REMOTE_HOST"],
            "PROXY_IP_WHITELIST":[],
            "AUTOMATION_ANALYTICS_LAST_GATHER":null,
            "AUTOMATION_ANALYTICS_GATHER_INTERVAL": 14400,
            "BROKER_DURABILITY":true}'
    body_format: json
  ignore_errors: ansible_check_mode

- name: Add Hosts Entry to Login to AWX if no DNS for {{ awx_debian_fqdn }}
  pause:
    seconds: 2
    prompt:
      "{{ ansible_default_ipv4.address }} {{ awx_debian_fqdn }}\n\n
       URL:      {{ awx_debian_url  }} \n
       Username: {{ awx_debian_admin }} \n
       Password: {{ awx_debian_pw }} \n"
